### ISSUE TITLE
请问怎么打包啊？

### ISSUE THREAD

**Issue by yuditxj** [ssbunny/enormous-turnip-designer#1]

**Comment by yuditxj** [comment]
gulp default的时候提示下面的错误，请问如何解决？
events.js:160
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Invalid labeled declaration

**Comment by ssbunny** [comment]
@yuditxj 不好意思，因为修改了 handontable 的源码，`gulpfile.js` 里的 `libsPath` 指定到了本地。下次修改的时候会更新过来。
暂时可使用 `dist` 里已经打包好的，或用 `gulp scripts-nolibs` 来打包。

**Comment by ssbunny** [comment]
@yuditxj [handsontable  源码修改情况](https://github.com/ssbunny/handsontable)。hot 这个框架 BUG 还挺多，因此我这个项目 BUG 也很多，目前只是我公司内部一个项目在用。你要是打算在生产环境使用要慎重。而且，目前没精力写文档，以后也未必有:)

**Comment by yuditxj** [comment]
嗯，我看qq的在线文档也是在handsontable基础上做的，感觉还有好多需要拓展的，gulp scripts-nolibs这样打包也出错events.js:160
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Invalid labeled declaration

**Comment by ssbunny** [comment]
@yuditxj qq的在线文档 BUG 也并不少。最近实在没空弄这个，不好意思。

**Comment by ssbunny** [comment]
@yuditxj `scripts-nolibs` 任务应该是没问题的。你是不是没 `npm install` ？
